{{- range $key, $entry := .Values.extraFileMappings -}}
{{- if $entry }}
apiVersion: v1
metadata:
  # Extract the filename portion only
  name: {{ printf (include "cloner.getExtraFilesUniqueName" $key) }}
{{- if $entry.useSecret }}
kind: Secret
type: Opaque
stringData:
{{- else }}
kind: ConfigMap
data:
{{- end }}
  {{- include "cloner.getFilenameFromPath" $key | nindent 2 }}: |
  {{- if $entry.tpl }}
    {{- tpl (tpl $entry.content $) $ | nindent 4 }}
  {{- else }}
    {{- $entry.content | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}